# number of threads to use
# to make this valid, you must set the number of cores when running snakemake pipeline.
# e.g. -j 10
THREADS: 10

# input and output data path
DATA:
  # path to directory for saving output files
  out_dir:
    outdir
  # path to genome sequence file
  genome:
    genome.fa
  # path to alignment file
  alignment:
    alignment.bam
  # path to text file containing line-seperated list of barcodes
  barcode:
    barcodes.txt

# cluster.py settings
CLUSTER:
  # number of genotypes in multiplexed sample
  n_genotypes: 10
  # ploidy of the organism of interest
  ploidy: 2
  # error rate correction parameter of probability model
  err_rate: 0.001
  # difference of likelihood to stop the iteration
  stop_criterion: 0.1
  # maximum number of iteration
  max_iter: 1000

# variant caller settings
VARIANT_CALLER:
  # variant caller to use. Choose "freebayes" or "strelka."
  caller: "strelka"
  # minimum quality score of variant, used only if the caller is "freebayes"
  min_qual: 0
  # whether to use low-GQX variants only, used only if the caller is "strelka"
  lowgqx: False

# vartrix settings
VARTRIX:
  # minimum mapping quality of read to use in vartrix
  mapq: 30

# troublet settings
TROUBLET:
  # doublet prior
  doublet_prior: 0.5
  # doublet posterior threshold
  doublet_threshold: 0.9
  # singlet posterior threshold
  singlet_threshold: 0.9