DATA:
  RESULT_PATH:
    /home/rotate/hansb/scATACseq_cluster/data/result5_qual_threshold/
  GENOME:
    /home/ambrosio/reference/refdata-cellranger-atac-hg19-1.2.0/fasta/genome.fa
  ALIGNMENTS:
    /home/rotate/hansb/scATACseq_cluster/test_demux/all_read_merge.bam
  BARCODES:
    /home/rotate/hansb/scATACseq_cluster/test_demux/all.unique.barcode.txt

SETTINGS:
  freebayes:
    -iXu -C 2 -q 20 -n 3 -E 1 -m 30 --min-coverage 20 --pooled-continuous
  bcftools:
    -e "QUAL < 100"
  vartrix:
    --mapq 20 --scoring-method coverage --threads 8
  souporcell:
    -k 4 -t 8
