[package]
name = "troublet"
version = "2.4.0"
authors = ["wheaton5 <whheaton@gmail.com>"]

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
hashbrown = "0.1"
fnv = "1.0.6"
statrs = "0.10.0"
